language: python
python:
  - '3.6.0'
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-opencv
  - sudo apt-get update

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O anaconda.sh;
  - export python_version=$TRAVIS_PYTHON_VERSION
  - bash anaconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels http://conda.binstar.org/omnia
  - conda create -y --name tefla python=$python_version
  - source activate tefla
  - pip install -U pip
  - pip install yapf==0.22.0
  - pip install coveralls
  - pip install requests[security]
  - pip install pytest==3.6.1
  - pip install pep8==1.7.0
  - pip install -U pytest-cov
  - pip install --upgrade pip setuptools wheel
  - pip install entrypoints
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install Cython==0.27.1
  - pip install pyaml==17.12.1
  - pip install git+https://github.com/lucasb-eyer/pydensecrf.git
  - pip install tensorflow==1.8.0
  - pip install opencv-python==3.4.1.15 
  - pip install mock==2.0.0 
  - python setup.py install

script:
  - python -m unittest discover tests/
  - bash tools/ci_build/ci_sanity.sh

after_success:
  - coveralls

matrix:
fast_finish: true
